# Generated by Claude Code on 2026-01-03

from django.db import migrations


def vincular_usuarios_a_empresa(apps, schema_editor):
    """
    Corrige usuários sem empresa vinculada.
    Vincula todos os usuários à primeira empresa disponível.
    """
    Usuario = apps.get_model('core', 'Usuario')
    Empresa = apps.get_model('empresas', 'Empresa')

    # Buscar usuários sem empresa
    usuarios_sem_empresa = Usuario.objects.filter(empresa__isnull=True)

    if not usuarios_sem_empresa.exists():
        print("[OK] Todos os usuarios ja tem empresa vinculada")
        return

    # Buscar primeira empresa ativa
    empresa = Empresa.objects.filter(ativa=True).first()

    if not empresa:
        print("[AVISO] Nenhuma empresa ativa encontrada! Pulando correcao...")
        return

    # Vincular usuários à empresa
    count = usuarios_sem_empresa.update(empresa=empresa)
    print(f"[OK] {count} usuario(s) vinculado(s) a empresa: {empresa.nome}")


def reverter_vinculo(apps, schema_editor):
    """Não faz nada na reversão (manter vínculos)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tornar_empresa_obrigatoria'),
        ('empresas', '0006_adicionar_google_maps_link'),
    ]

    operations = [
        migrations.RunPython(vincular_usuarios_a_empresa, reverter_vinculo),
    ]
