# Generated by Django 5.2.9 on 2026-01-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vincular_usuarios_sem_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(blank=True, help_text='Token para ativação de conta', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activation_token_created',
            field=models.DateTimeField(blank=True, help_text='Data de criação do token', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='Indica se a conta foi ativada'),
        ),
    ]
