# Generated by Django 5.2.9 on 2026-02-15 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL da Página')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Referenciador')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Sessão')),
            ],
            options={
                'verbose_name': 'Visualização de Página',
                'verbose_name_plural': 'Visualizações de Páginas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='landing_pag_timesta_8f327d_idx'), models.Index(fields=['page_url'], name='landing_pag_page_ur_aee2f4_idx'), models.Index(fields=['session_id'], name='landing_pag_session_393107_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click_cta', 'Clique em CTA'), ('section_view', 'Visualização de Seção'), ('faq_open', 'Abertura de FAQ'), ('scroll_depth', 'Profundidade de Scroll'), ('time_on_section', 'Tempo em Seção'), ('plan_click', 'Clique em Plano'), ('whatsapp_click', 'Clique no WhatsApp'), ('contact_click', 'Clique em Contato'), ('menu_click', 'Clique no Menu')], max_length=50, verbose_name='Tipo de Evento')),
                ('event_data', models.JSONField(default=dict, verbose_name='Dados do Evento')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL da Página')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
            ],
            options={
                'verbose_name': 'Evento de Usuário',
                'verbose_name_plural': 'Eventos de Usuários',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='landing_use_timesta_9d7019_idx'), models.Index(fields=['event_type'], name='landing_use_event_t_929e36_idx'), models.Index(fields=['session_id'], name='landing_use_session_b80150_idx')],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('nome_negocio', models.CharField(max_length=200, verbose_name='Nome do Negócio')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('notificado', models.BooleanField(default=False, verbose_name='Já foi notificado?')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Internas')),
            ],
            options={
                'verbose_name': 'Lead da Lista de Espera',
                'verbose_name_plural': 'Lista de Espera',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='landing_wai_created_fb282b_idx'), models.Index(fields=['email'], name='landing_wai_email_a630b2_idx'), models.Index(fields=['notificado'], name='landing_wai_notific_7c9c3e_idx')],
            },
        ),
    ]
