# Generated by Django 5.2.9 on 2025-12-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_status'),
        ('empresas', '0002_profissional_cor_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMensagemBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Telefone do cliente que enviou', max_length=20)),
                ('mensagem_original', models.TextField(help_text='Mensagem original do WhatsApp')),
                ('intencao_detectada', models.CharField(choices=[('agendar', 'Agendar'), ('cancelar', 'Cancelar'), ('reagendar', 'Reagendar'), ('consultar', 'Consultar'), ('confirmar', 'Confirmar'), ('outro', 'Outro')], max_length=20)),
                ('dados_extraidos', models.JSONField(default=dict, help_text='Dados extraídos pela IA')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('parcial', 'Parcial')], max_length=20)),
                ('resposta_enviada', models.TextField(help_text='Resposta enviada ao cliente')),
                ('erro_detalhes', models.TextField(blank=True, help_text='Detalhes do erro se houver')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(blank=True, help_text='Agendamento criado/modificado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.agendamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_bot', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Log de Mensagem do Bot',
                'verbose_name_plural': 'Logs de Mensagens do Bot',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['telefone', '-criado_em'], name='agendamento_telefon_f50ea5_idx'), models.Index(fields=['empresa', 'intencao_detectada'], name='agendamento_empresa_de5535_idx')],
            },
        ),
    ]
