# Generated by Django 5.2.9 on 2025-12-23 01:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_logmensagembot'),
        ('clientes', '0002_alter_cliente_unique_together'),
        ('empresas', '0002_profissional_cor_hex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], help_text='Com que frequência o agendamento se repete', max_length=20)),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de dias da semana (0=seg, 6=dom). Ex: [0,2,4] = seg/qua/sex')),
                ('dia_mes', models.IntegerField(blank=True, help_text='Para recorrência mensal: dia do mês (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('hora_inicio', models.TimeField(help_text='Horário do agendamento')),
                ('data_inicio', models.DateField(help_text='A partir de quando gerar os agendamentos')),
                ('data_fim', models.DateField(blank=True, help_text='Até quando gerar (deixe vazio para infinito)', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se False, para de gerar novos agendamentos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_recorrentes', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_recorrentes', to='empresas.empresa')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_recorrentes', to='empresas.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_recorrentes', to='empresas.servico')),
            ],
            options={
                'verbose_name': 'Agendamento Recorrente',
                'verbose_name_plural': 'Agendamentos Recorrentes',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='agendamento_empresa_5a202c_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='agendamento_data_in_f1c1f3_idx')],
            },
        ),
    ]
