# Generated by Django 5.2.9 on 2025-12-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamentorecorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='notificado_1dia',
            field=models.BooleanField(default=False, help_text='Se já enviou notificação 1 dia antes'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='notificado_1hora',
            field=models.BooleanField(default=False, help_text='Se já enviou notificação 1 hora antes'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='origem',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Bot'), ('manual', 'Manual (Admin/Dashboard)'), ('site', 'Site'), ('telefone', 'Telefone')], default='manual', help_text='Como o agendamento foi criado', max_length=20),
        ),
    ]
