# Generated by Django 5.2.9 on 2025-12-25 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_empresa_onboarding_completo_empresa_onboarding_etapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('essencial', 'Essencial'), ('profissional', 'Profissional'), ('empresarial', 'Empresarial')], help_text='Tipo de plano', max_length=50, unique=True)),
                ('descricao', models.TextField(help_text='Descrição do que está incluído no plano')),
                ('preco_mensal', models.DecimalField(decimal_places=2, help_text='Preço em R$ por mês', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_profissionais', models.IntegerField(default=1, help_text='Quantidade máxima de profissionais', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_agendamentos_mes', models.IntegerField(default=500, help_text='Máximo de agendamentos por mês', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_usuarios', models.IntegerField(default=1, help_text='Quantidade máxima de usuários (logins)', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_servicos', models.IntegerField(default=10, help_text='Quantidade máxima de serviços cadastrados', validators=[django.core.validators.MinValueValidator(1)])),
                ('stripe_price_id', models.CharField(blank=True, help_text='Price ID do produto no Stripe (ex: price_1ABC...)', max_length=255, null=True)),
                ('asaas_plan_id', models.CharField(blank=True, help_text='ID do plano no Asaas (se aplicável)', max_length=255, null=True)),
                ('trial_dias', models.IntegerField(default=7, help_text='Dias de trial gratuito', validators=[django.core.validators.MinValueValidator(0)])),
                ('permite_relatorios_avancados', models.BooleanField(default=False)),
                ('permite_integracao_contabil', models.BooleanField(default=False)),
                ('permite_multi_unidades', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_exibicao', models.IntegerField(default=0, help_text='Ordem na página de preços')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem_exibicao', 'preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial (Teste Grátis)'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa por Falta de Pagamento'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='trial', help_text='Status atual da assinatura', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, help_text='Data de criação da assinatura')),
                ('data_expiracao', models.DateTimeField(help_text='Data em que a assinatura expira (renova mensalmente)')),
                ('trial_ativo', models.BooleanField(default=True, help_text='Se está em período de trial')),
                ('ultimo_pagamento', models.DateTimeField(blank=True, help_text='Data do último pagamento recebido', null=True)),
                ('proximo_vencimento', models.DateField(blank=True, help_text='Data do próximo vencimento', null=True)),
                ('gateway', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('asaas', 'Asaas'), ('manual', 'Manual')], help_text='Gateway de pagamento utilizado', max_length=50)),
                ('subscription_id_externo', models.CharField(blank=True, help_text='ID da assinatura no gateway (Stripe/Asaas)', max_length=255)),
                ('customer_id_externo', models.CharField(blank=True, help_text='ID do cliente no gateway', max_length=255)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(help_text='Empresa que possui esta assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='empresas.empresa')),
                ('plano', models.ForeignKey(help_text='Plano contratado', on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='assinaturas.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('gateway', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pagamentos', to='assinaturas.assinatura')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Histórico de Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
