# Generated by Django 5.2.9 on 2026-01-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_adicionar_novas_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='permite_lembrete_1_dia',
            field=models.BooleanField(default=True, help_text='Permite enviar lembrete 1 dia (24h) antes do agendamento'),
        ),
        migrations.AddField(
            model_name='plano',
            name='permite_lembrete_1_hora',
            field=models.BooleanField(default=False, help_text='Permite enviar lembrete 1 hora antes do agendamento (plano superior)'),
        ),
    ]
