# Generated by Django 5.2.9 on 2026-01-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0003_adicionar_campos_lembretes'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='permite_whatsapp_bot',
            field=models.BooleanField(default=True, help_text='Permite usar o WhatsApp Bot para agendamentos automáticos'),
        ),
    ]
