# Generated by Django 5.2.9 on 2025-12-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0002_profissional_cor_hex'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'telefone')},
        ),
    ]
