# Generated by Django 5.2.9 on 2026-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='origem',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Bot'), ('manual', 'Manual (Dashboard)'), ('site', 'Site Público'), ('importacao', 'Importação')], default='manual', help_text='Canal de origem do cliente', max_length=20),
        ),
    ]
