# Generated by Django 5.2.9 on 2025-12-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cor_hex',
            field=models.CharField(default='#1e3a8a', help_text='Cor dos eventos deste profissional no calendário (ex: #3b82f6)', max_length=7),
        ),
    ]
