# Generated by Django 5.2.9 on 2025-12-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_profissional_cor_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do feriado ou horário especial')),
                ('descricao', models.CharField(help_text='Ex: Natal, Ano Novo, Carnaval', max_length=200)),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado - Fechado'), ('especial', 'Horário Especial')], default='feriado', max_length=10)),
                ('hora_abertura', models.TimeField(blank=True, help_text='Horário de abertura (se horário especial)', null=True)),
                ('hora_fechamento', models.TimeField(blank=True, help_text='Horário de fechamento (se horário especial)', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_especiais', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Data Especial',
                'verbose_name_plural': 'Datas Especiais',
                'ordering': ['empresa', 'data'],
                'unique_together': {('empresa', 'data')},
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='0=Segunda, 6=Domingo')),
                ('hora_abertura', models.TimeField(help_text='Horário de abertura')),
                ('hora_fechamento', models.TimeField(help_text='Horário de fechamento')),
                ('intervalo_inicio', models.TimeField(blank=True, help_text='Início do intervalo (opcional)', null=True)),
                ('intervalo_fim', models.TimeField(blank=True, help_text='Fim do intervalo (opcional)', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_funcionamento', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['empresa', 'dia_semana'],
                'unique_together': {('empresa', 'dia_semana')},
            },
        ),
    ]
