# Generated by Django 5.2.9 on 2025-12-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_dataespecial_horariofuncionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='onboarding_completo',
            field=models.BooleanField(default=False, help_text='Se a empresa completou o wizard de configuração inicial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='onboarding_etapa',
            field=models.IntegerField(default=0, help_text='Etapa atual do onboarding (0-4)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='origem_cadastro',
            field=models.CharField(blank=True, choices=[('manual', 'Cadastro Manual'), ('checkout', 'Checkout Automático'), ('indicacao', 'Indicação')], default='checkout', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_conectado',
            field=models.BooleanField(default=False, help_text='Se WhatsApp está conectado e funcionando'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_instance_id',
            field=models.CharField(blank=True, help_text='ID da instância no provedor WhatsApp', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Número WhatsApp conectado (com código do país)', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp_token',
            field=models.CharField(blank=True, help_text='Token da Evolution API / Z-API', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
