# Generated by Django 5.2.9 on 2025-12-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_onboarding_completo_empresa_onboarding_etapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_api_url', models.URLField(blank=True, help_text='URL base da Evolution API (ex: https://evolution.seuservidor.com)', max_length=500)),
                ('evolution_api_key', models.CharField(blank=True, help_text='API Key global da Evolution API', max_length=255)),
                ('instance_name', models.CharField(blank=True, help_text='Nome único da instância (slug da empresa ou personalizado)', max_length=255)),
                ('instance_token', models.CharField(blank=True, help_text='Token específico da instância (gerado pela Evolution)', max_length=255)),
                ('status', models.CharField(choices=[('nao_configurado', 'Não Configurado'), ('aguardando_qr', 'Aguardando QR Code'), ('conectando', 'Conectando'), ('conectado', 'Conectado'), ('desconectado', 'Desconectado'), ('erro', 'Erro na Conexão')], default='nao_configurado', help_text='Status atual da conexão WhatsApp', max_length=20)),
                ('qr_code', models.TextField(blank=True, help_text='QR Code em base64 para conectar WhatsApp')),
                ('qr_code_expira_em', models.DateTimeField(blank=True, help_text='Data de expiração do QR Code', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL do webhook configurado na Evolution API', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret para validar webhooks recebidos', max_length=255)),
                ('numero_conectado', models.CharField(blank=True, help_text='Número WhatsApp conectado (com DDI)', max_length=20)),
                ('nome_perfil', models.CharField(blank=True, help_text='Nome do perfil WhatsApp conectado', max_length=255)),
                ('foto_perfil_url', models.URLField(blank=True, help_text='URL da foto de perfil do WhatsApp', max_length=500)),
                ('ativo', models.BooleanField(default=True, help_text='Se a integração está ativa')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, help_text='Última vez que sincronizou status com Evolution API', null=True)),
                ('ultimo_erro', models.TextField(blank=True, help_text='Último erro ocorrido na integração')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Dados extras da Evolution API')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(help_text='Empresa dona desta configuração', on_delete=django.db.models.deletion.CASCADE, related_name='config_whatsapp', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp',
                'verbose_name_plural': 'Configurações WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
