# Generated by Django 5.2.9 on 2026-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_configuracaowhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Link do Google Maps para localização da empresa', max_length=500),
        ),
    ]
