# Generated by Django 5.2.9 on 2026-01-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_adicionar_google_maps_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=255, unique=True)),
                ('evolution_instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('webhook_token', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Instância WhatsApp',
                'verbose_name_plural': 'Instâncias WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
