# Generated by Django 5.2.9 on 2026-01-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_add_whatsappinstance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profissional',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
